"""
    Highly Divisible Triangular Number

The sequence of triangle numbers is generated by adding the natural numbers.
So the 7th triangle number would be 1+2+3+4+5+6+7 = 28. The first ten terms
would be 1,3,6,10,15,21,28,36,45,55,...
What is the value of the first triangle number to have over 500 divisors?

# Input parameters:
- `n` : the triangle number must have over n divisors.

# Examples/Tests:
```julia
problem_012(5)          # returns 28
problem_012(333)        # returns 17907120
problem_012(500)        # returns 76576500
problem_012(-1)         # throws DomainError
```

# Reference
- https://projecteuler.net/problem=12

Contributed by: [Praneeth Jain](https://www.github.com/PraneethJain)
"""
function problem_012(n::Int)
    n < 1 && throw(DomainError("n must be a natural number"))
    i = 1
    while num_divisors(i * (i + 1) ÷ 2) <= n
        i += 1
    end
    return i * (i + 1) ÷ 2
end
