name: JuliaFormatter
on: [push, pull_request]

jobs:
  format:
    name: Format with JuliaFormatter.jl
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: julia-actions/julia-format@master
      with:
        args: -v .
